home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [

    path("", views.index, name='index'),
    path("about/", views.about1, name='about'),
    path("admin123/", views.admin_page, name='admn'),
    path("contact/", views.contact, name='contact'),
    path("facilities/", views.facility, name='facility'),

    path("gallery/", views.gallery1, name='gallery'),
    path("gallery/add", views.gallery_add, name='gal-add'),
    path('gallery/<int:pk>', views.gallery2 , name='gal-sec'),
    path("gallery/section/add", views.gallery_type_add, name='gal-sec-add'),
    path('gallery/list', views.gallery_list , name='gal-list'),
    path('delete/<int:pk>', views.del_img , name='img-del'),
    path('delete/section/<int:pk>', views.del_gal , name='sect-del'),

    path("article/add", views.article_form, name='article-add'),
    path("articles", views.article_page, name='article-all'),
    path("article/list", views.article_list, name='article-list'),
    path("article/<int:pk>", views.articles, name='article'),
    path("article/del/<int:pk>", views.article_delete, name='article-del'),

    path("news/", views.news_page, name='news-all'),
    path("news/add", views.news_form, name='news-add'),
    path("news/list", views.news_list, name='news-list'),
    path("news/del/<int:pk>", views.news_delete, name='news-del'),

    path("teacher/", views.teacher_page, name='tech'),
    path("teacher/add", views.teacher_form, name='tech-add'),
    path("teacher/list", views.teacher_list, name='tech-list'),
    path("teacher/del/<int:pk>", views.teacher_delete, name='tech-del'),

]

school/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('home.urls', namespace="home")),
    path('admin/', admin.site.urls),

 ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
import datetime


class gallery_type(models.Model):
    name = models.CharField(max_length=  40)
    description = models.TextField(blank=True)
    type_image = models.FileField(upload_to='gallery/' , blank=True, null=True)

    def __str__(self):
        return self.name


class gallery (models.Model):
    name = models.CharField(max_length=40)
    category = models.ForeignKey(gallery_type , on_delete=models.CASCADE)
    dated_on = models.DateField(default=datetime.date.today)
    image = models.FileField(upload_to='gallery/' , blank=True, null=True)

    def __str__(self):
        return self.name


class article (models.Model):
    title = models.CharField(max_length=40)
    description = models.TextField(blank=True)
    author = models.CharField(max_length=40)
    author_post = models.CharField(max_length=40)
    dated_on = models.DateField(default=datetime.date.today)
    image = models.FileField(upload_to='article/' , blank=True, null=True)

    def __str__(self):
        return self.title


class news(models.Model):
    title = models.CharField(max_length=15)
    description = models.TextField(blank=True)
    date = models.DateField(default=datetime.date.today)
    news_image = models.FileField(upload_to='news/')
    news_file = models.FileField(upload_to='news/', blank=True)

    def __str__(self):
        return self.title


class teacher(models.Model):
    name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)
    tech_img = models.FileField(upload_to='news/')

    def __str__(self):
        return self.name

home/forms.py
from django import forms
from .models import  gallery, gallery_type, article, news, teacher


class GalleryForm(forms.ModelForm):
    class Meta:
        model = gallery
        fields = ('name', 'category', 'image' )


class GalleryTypeForm(forms.ModelForm):
    class Meta:
        model = gallery_type
        fields = ('name',  'description', 'type_image'  )


class ArticleForm(forms.ModelForm):
    class Meta:
        model = article
        fields = ('title', 'description','author','author_post', 'image' )


class NewsForm(forms.ModelForm):
    class Meta:
        model = news
        fields = ('title', 'description', 'news_image',  'news_file' )


class TeacherForm(forms.ModelForm):
    class Meta:
        model = teacher
        fields = ('name', 'subject', 'tech_img' )

home/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.http import HttpResponse
from .models import gallery, gallery_type, article, news, teacher
from .forms import GalleryForm, GalleryTypeForm, ArticleForm, NewsForm,  TeacherForm

def index(request):
    articles = article.objects.all().order_by('-id')[:3]
    items = news.objects.all().order_by('-id')[:5]
    return render(request, 'home/dash.html', {'items': items, 'articles' : articles  })


def user_all(request):
        course_id = request.GET.get("course_id")
        upcoming_li=[]
        batch_qs=list(Batch.objects.filter(course_name_id=course_id).values())
        user_qs=User.objects.get(id=request.user.id)
        user_batch_qs=list(user_qs.batch.all().values("id"))
        now = datetime.now()
        now1=now+timedelta(days = 7)
        lst = []
        pending=[]
        completed=[]
        dic={}
        for i in user_batch_qs:
            for j in batch_qs:
                if i["id"] == j["id"]:
                    timing = ast.literal_eval(j["timing"])
                    if timing:
                        data = upcoming_classes(timing)
                        dic["course_id"]=j["course_name_id"]
                        course_qs=Course.objects.get(id=j["course_name_id"])
                        dic["course_name"]=course_qs.title
                        dic["upcoming_classes"]=data
                        data1 = completed_classes(timing)
                        dic["completed_classes"]=data1
                        dic["batch_id"]=i["id"]
                        dic["batch_name"]=j["batch_name"]
                        dic["online_link"]=j["online_link"]
        return render (request, 'teacher.html' , {'all_teachers': all_teachers } )




def user_all(request):
        course_id = 2
        upcoming_li=[]
        batch_qs=list(Batch.objects.filter(course_name_id=course_id).values())
        user_qs=User.objects.get(id=85)
        user_batch_qs=list(user_qs.batch.all().values("id"))
        now = datetime.now()
        now1=now+timedelta(days = 7)
        lst = []
        pending=[]
        completed=[]
        dic={}
        links = []
        for i in user_batch_qs:
            for j in batch_qs:
                if i["id"] == j["id"]:
                    timing = ast.literal_eval(j["timing"])
                    if timing:
                        data = upcoming_classes(timing)
                        dic["course_id"]=j["course_name_id"]
                        course_qs=Course.objects.get(id=j["course_name_id"])
                        dic["course_name"]=course_qs.title
                        dic["upcoming_classes"]=data
                        data1 = completed_classes(timing)
                        dic["completed_classes"]=data1
                        dic["batch_id"]=i["id"]
                        dic["batch_name"]=j["batch_name"]
                        links.append(j["online_link"])
        return render (request, 'student.html' , {'data':dic , 'link':links } )




def admin_page(request):
    return render(request, 'home/admin.html')

def about1(request):
    return render(request, 'home/about.html')


def contact(request):
    return render(request, 'home/contact.html')


def facility(request):
    return render(request, 'home/facilities.html')


def gallery1(request):
    items = gallery_type.objects.all().order_by('-pk')
    return render(request, 'home/gallery.html', {'items': items })



def gallery2(request, pk):
    item = gallery_type.objects.get(pk=pk)
    items = gallery.objects.filter(category=item).order_by('-id')
    return render(request, 'home/gallery_section.html', {'items': items , "main_item": item })


def gallery_type_add(request):
    if request.method == "POST":
        form = GalleryTypeForm(request.POST,request.FILES)
        if form.is_valid():
            form.save(True)
            return redirect('home:index')
        else:
            return HttpResponse("Nhi hua")
    else:
        return render(request, 'home/gallery_type_form.html')


def gallery_add(request):
    form = GalleryForm()
    if request.method == "POST":
        form = GalleryForm(request.POST,request.FILES)
        if form.is_valid():
            form.save(True)
            return redirect('home:index')
        else:
            return HttpResponse("Nhi hua")
    else:
        return render(request, 'home/gallery_form.html', {"form": form})


def gallery_list(request):
    sections = gallery_type.objects.all().order_by('-pk')
    items = gallery.objects.all().order_by('-pk')
    return render(request, 'home/images_list.html', {"items": items, "sections": sections })


def del_img(request,pk):
    img = gallery.objects.get(pk=pk)
    img.delete()
    items = gallery.objects.all().order_by('-pk')
    return render(request, 'home/images_list.html', {"items": items } )


def del_gal(request,pk):
    sect = gallery_type.objects.get(pk=pk)
    imgs = gallery.objects.filter(category=sect)
    for i in imgs:
        i.delete()
    sect.delete()
    items = gallery.objects.all().order_by('-pk')
    sections = gallery_type.objects.all().order_by('-pk')
    return render(request, 'home/images_list.html', {"items": items,  "sections": sections } )



def article_form(request):
    if request.method == "POST":
        form = ArticleForm(request.POST,request.FILES)
        if form.is_valid():
            form.save(True)
            return redirect('home:article-list')
        else:
            return HttpResponse("Nhi hua")
    return render(request, 'home/article_form.html')


def articles(request, pk):
    art = article.objects.get(pk=pk)
    return render(request, 'home/article.html', {'art': art} )


def article_page(request):
    items = article.objects.all()
    return render(request, 'home/articles.html', {'items': items} )


def article_list(request):
    items = article.objects.all()
    return render(request, 'home/article_list.html', {'items': items} )


def article_delete(request,pk):
    item = article.objects.get(pk=pk)
    item.delete()
    items = article.objects.all()
    return render(request, 'home/article_list.html', {'items': items} )


def news_page(request):
    items = news.objects.all().order_by('-id')
    return render(request, 'home/news.html', {'items': items  })


def news_form(request):
    if request.method == "POST":
        form = NewsForm(request.POST,request.FILES)
        if form.is_valid():
            form.save(True)
            return redirect('home:news-list')
        else:
            return HttpResponse("Nhi hua")
    return render(request, 'home/news_form.html')


def news_list(request):
    items = news.objects.all()
    return render(request, 'home/news_list.html', {'items': items} )


def news_delete(request,pk):
    item = news.objects.get(pk=pk)
    item.delete()
    items = news.objects.all()
    return render(request, 'home/news_list.html', {'items': items} )


def teacher_page(request):
    items = teacher.objects.all()
    return render(request, 'home/teacher.html', {'items': items} )


def teacher_form(request):
    if request.method == "POST":
        form = TeacherForm(request.POST,request.FILES)
        if form.is_valid():
            form.save(True)
            return redirect('home:tech-list')
        else:
            return HttpResponse("Nhi hua")
    return render(request, 'home/tech_form.html')


def teacher_list(request):
    items = teacher.objects.all()
    return render(request, 'home/tech_list.html', {'items': items} )


def teacher_delete(request,pk):
    item = teacher.objects.get(pk=pk)
    item.delete()
    items = teacher.objects.all()
    return render(request, 'home/tech_list.html', {'items': items} )

home/templates/home/admin.html
{% extends 'index.html' %}
{% block head %}
    <title> Mt. Carmel | Admin  </title>
{% endblock %}

{% block body %}


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco_navbar ftco-navbar-light" id="ftco-navbar">
	    <div class="container d-flex align-items-center">
	    	<a class="navbar-brand" href="{% url 'home:index' %}">  Mount Carmel Convent School  </a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>
	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	        	<li class="nav-item"><a href="{% url 'home:index' %}" class="nav-link pl-0">Home</a></li>
	        	<li class="nav-item"><a href="{% url 'home:about' %}" class="nav-link">About</a></li>
	        	<li class="nav-item"><a href="#" class="nav-link"> Admissions </a></li>
	        	<li class="nav-item"><a href="#" class="nav-link"> Academics </a></li>
	        	<li class="nav-item"><a href="{% url 'home:gallery' %}" class="nav-link"> Gallery </a></li>
	          <li class="nav-item"><a href="{% url 'home:contact' %}" class="nav-link">Contact</a></li>
	        </ul>
	      </div>
	    </div>
	  </nav>

		<section class="ftco-section ftco-no-pt ftc-no-pb" style="padding:2em 0">
			<div class="container">
				<div class="row">
					<div class="col-md-8 order-md-last wrap-about py-5 wrap-about bg-light">
						<div class="text px-4 ftco-animate">
	          	<h2 class="mb-4"> Welcome to Mount Carmel Convent School</h2>
							<p>

 				                1. <a href="{% url 'home:article-add' %}">    Add Article     </a> <br>
                                2. <a href="{% url 'home:article-list' %}">   Delete Article/Article List  </a> <br>
                                <br>
                                3.  <a href="{% url 'home:gal-sec-add' %}">   Add Gallery Section    </a> <br>
                                4.  <a href="{% url 'home:gal-add' %}">   Add Images to a Gallery Section   </a> <br>
                                5.  <a href="{% url 'home:gal-list' %}">  Delete Image/Gallery Section  </a> <br>
                                <br>
                                6.  <a href="{% url 'home:news-add'  %}">  Add News  </a> <br>
                                7.  <a href="{% url 'home:news-list' %}">  Delete News / News List  </a> <br>
                                <br>


							</p>

							<!--p><a href="#" class="btn btn-secondary px-4 py-3">Read More</a></p -->
						</div>
					</div>
</div>
</div>
</section>


{% endblock %}

home/templates/home/article_list.html
{% extends 'index.html' %}

{% block head %}
    <title> St. Austin's | Articles  </title>
{% endblock %}

{% block body %}

<style>
p    {font-size: larger;}
</style>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco_navbar ftco-navbar-light" id="ftco-navbar">
	    <div class="container d-flex align-items-center">
	    	<a class="navbar-brand" href="{% url 'home:index' %}"> Mount Carmel Convent School </a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>
	      <!-- <p class="button-custom order-lg-last mb-0"><a href="appointment.html" class="btn btn-secondary py-2 px-3">Make An Appointment</a></p> -->
	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	        	<li class="nav-item"><a href="{% url 'home:index' %}" class="nav-link pl-0">Home</a></li>
	        	<li class="nav-item"><a href="{% url 'home:about' %}" class="nav-link">About</a></li>
	        	<li class="nav-item"><a href="#" class="nav-link"> Admissions </a></li>
	        	<li class="nav-item"><a href="#" class="nav-link"> Academics </a></li>
	        	<li class="nav-item"><a href="{% url 'home:gallery' %}" class="nav-link"> Gallery </a></li>
	          <li class="nav-item"><a href="{% url 'home:contact' %}" class="nav-link">Contact</a></li>
	        </ul>
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->


<section class="probootstrap-section" style="padding:4em 0;">
        <div class="container">
		<h2> Articles List </h2>
        <p>   You may delete the articles that no longer have to be present on the Website.
        </p>
<table class="table">
						  <thead class="thead-primary">
						    <tr>
						      <th> Sr. No. </th>
						      <th> Name   </th>
						      <th> &nbsp;  </th>
						      <th> &nbsp;  </th>

						    </tr>
						  </thead>
						  <tbody>
						    {% for item in items %}
						    <tr class="alert" role="alert">
						        <td> {{ forloop.counter }} </td>
						      <td> 	<div class="email">
						      		     {{ item.title }} <br>
						      		     -{{ item.author }}
						      	    </div>
						      </td>
						      <td>  <!--div class="img" style="background-image: url();"></div> 	</td-->
						          <img src="{{ item.image.url }}" height="90px" > </img>
						      </td>
						      <td>
						      	<!--a href="  "
						      	<span aria-hidden="true"><i class="fa fa-trash"></i></span>  -->
				            	<a href="{% url 'home:article-del'  item.pk %}">
				            	  Delete
				          	    <a>
				        	  </td>
						    </tr>
                            {% endfor %}
						  </tbody>
						</table>
   </div>
</section>


{% endblock %}

home/templates/home/facilities.html
{% extends 'index.html' %}
{% block title %}
    Mt. Carmel | Facilities
{% endblock %}

{% block body %}

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco_navbar ftco-navbar-light" id="ftco-navbar">
	    <div class="container d-flex align-items-center">
	    	<a class="navbar-brand" href="index.html">Kiddos</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>
	      <!-- <p class="button-custom order-lg-last mb-0"><a href="appointment.html" class="btn btn-secondary py-2 px-3">Make An Appointment</a></p> -->
	       <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	        	<li class="nav-item  active"><a href="{% url 'home:index' %}" class="nav-link pl-0">Home</a></li>
	        	<li class="dropdown nav-item" >
	        	     <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" >    About   </a>
	        	  <ul class="dropdown-menu">
                  <li class="nav-item"><a href="{% url 'home:about' %}"> About Us </a></li>
                  <li class="nav-item"><a href="#" >    Principal's Desk </a></li>
                  <li class="nav-item"><a href="#" >    Faculty          </a></li>
                  <li class="nav-item"><a href="{% url 'home:facility' %}" >    Facilities       </a></li>
                  </ul>
                </li>
	        	<li class="nav-item"><a href="#" class="nav-link"> Admissions </a></li>

	        	<li class="dropdown nav-item" >
	        	     <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" >   Academics  </a>
	        	  <ul class="dropdown-menu">
                  <li class="nav-item"><a href="{% url 'home:about' %}"> Scholastic </a></li>
                  <li class="nav-item"><a href="#" >    Non Scholastic </a></li>
                  <li class="nav-item"><a href="{% url 'home:article-all' %}" >    Articles          </a></li>
                  <li class="nav-item"><a href="#" >    News       </a></li>
                  </ul>
                </li>
	        	<li class="nav-item"><a href="{% url 'home:gallery' %}" class="nav-link"> Gallery </a></li>
	          <li class="nav-item"><a href="{% url 'home:contact' %}" class="nav-link">Contact</a></li>
	        </ul>
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->

    <section class="hero-wrap hero-wrap-2" style="background-image: url('/static/images/bg_2.jpg');">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-2 bread">Our Facilities</h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'home:index' %}">Home
            <i class="ion-ios-arrow-forward"></i></a></span> <span> Facilities <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>

		<section class="ftco-section">
			<div class="container">
				<div class="row">
					<div class="col-md-12 course d-lg-flex ftco-animate">
						<div class="img" style="background-image: url(/static/images/course-1.jpg);"></div>
						<div class="text bg-light p-4" style="color: rgba(0,0,0,0.8);">
							<h3><a href="#">  BEYOND CLASSROOM </a></h3>
							<p>It is well known fact that children learn better when they practically experience the book imparted knowledge.This is done through multimedia such as smart class, power point slides and outdoor tutorials.
                                The practical and intellectual skills are shaped through carefully chosen activities of classroom and beyond.It is believed that learning musical instruments increases the multitasking ability of our brain, hence we pay utmost attention in our child’s music lessons.
                            </p>
						</div>
					</div>
					<div class="col-md-12 course d-lg-flex ftco-animate">
						<div class="text bg-light p-4" style="color: rgba(0,0,0,0.8);">
							<h3><a href="#"> TRANSPORT  </a></h3>
							<p> We understand the concern of every parents when it comes to time, transport and safety. For the same reason, we have a secure and trusted transport facility. Safety of our children is our top priority. </p>
						</div>
						<div class="img" style="background-image: url(/static/images/course-2.jpg);"></div>

					</div>
					<div class="col-md-12 course d-lg-flex ftco-animate">
						<div class="img" style="background-image: url(/static/images/course-3.jpg);"></div>
						<div class="text bg-light p-4" style="color: rgba(0,0,0,0.8);">
							<h3><a href="#"> COMPUTER LAB </a></h3>
							<p> We keep our children updated on keys of technology. The knowledge of computer helps us to navigate the rapidly changing technology driven world. Beginning right from 1st  standard, we make sure every child is well equipped with the skills on computer. </p>
						</div>
					</div>
					<div class="col-md-12 course d-lg-flex ftco-animate">
						<div class="text bg-light p-4" style="color: rgba(0,0,0,0.8);">
							<h3><a href="#"> SPORTS </a></h3>
							<p> Along with academic gains, physical health plays an important role in mental development. At our institution children get to choose from wide range of options among both indoor and outdoor games. </p>
						</div>
						<div class="img" style="background-image: url(/static/images/course-4.jpg);"></div>
					</div>
					<div class="col-md-12 course d-lg-flex ftco-animate">
						<div class="img" style="background-image: url(/static/images/course-5.jpg);"></div>
						<div class="text bg-light p-4" style="color: rgba(0,0,0,0.8);">
							<h3><a href="#"> Swimming Classes </a></h3>
							<p>Separated they live in. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country</p>
						</div>
					</div>
					<div class="col-md-12 course d-lg-flex ftco-animate">
						<div class="text bg-light p-4" style="color: rgba(0,0,0,0.8);">
							<h3><a href="#"> Sandpits for Kids </a></h3>
							<p> ????? <br> Separated they live in. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country</p>
						</div>
						<div class="img" style="background-image: url(/static/images/course-6.jpg);"></div>
					</div>
					<div class="col-md-12 course d-lg-flex ftco-animate">
						<div class="img" style="background-image: url(/static/images/course-6.jpg);"></div>
						<div class="text bg-light p-4" style="color: rgba(0,0,0,0.8);">
							<h3><a href="#"> 	LIBRARY  </a></h3>
							<p> ‘Knowledge is power’, and to open the doorway to the grand halls of language and learning, we provide our children with a fully packed library. Here, the children get to develop their reading skills and knowledge of English language. </p>
						</div>
					</div>





				</div>
			</div>
		</section>





{% endblock %}

home/templates/home/news.html
{% extends 'index.html' %}
{% block title %}
    Mt. Carmel | Current News
{% endblock %}

{% block body %}

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco_navbar ftco-navbar-light" id="ftco-navbar">
	    <div class="container d-flex align-items-center">
	    	<a class="navbar-brand" href="index.html">Kiddos</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>
	      <!-- <p class="button-custom order-lg-last mb-0"><a href="appointment.html" class="btn btn-secondary py-2 px-3">Make An Appointment</a></p> -->
	       <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	        	<li class="nav-item  active"><a href="{% url 'home:index' %}" class="nav-link pl-0">Home</a></li>
	        	<li class="dropdown nav-item" >
	        	     <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" >    About   </a>
	        	  <ul class="dropdown-menu">
                  <li class="nav-item"><a href="{% url 'home:about' %}"> About Us </a></li>
                  <li class="nav-item"><a href="#" >    Principal's Desk </a></li>
                  <li class="nav-item"><a href="#" >    Faculty          </a></li>
                  <li class="nav-item"><a href="{% url 'home:facility' %}" >    Facilities       </a></li>
                  </ul>
                </li>
	        	<li class="nav-item"><a href="#" class="nav-link"> Admissions </a></li>

	        	<li class="dropdown nav-item" >
	        	     <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" >   Academics  </a>
	        	  <ul class="dropdown-menu">
                  <li class="nav-item"><a href="{% url 'home:about' %}"> Scholastic </a></li>
                  <li class="nav-item"><a href="#" >    Non Scholastic </a></li>
                  <li class="nav-item"><a href="{% url 'home:article-all' %}" >    Articles          </a></li>
                  <li class="nav-item"><a href="#" >    News       </a></li>
                  </ul>
                </li>
	        	<li class="nav-item"><a href="{% url 'home:gallery' %}" class="nav-link"> Gallery </a></li>
	          <li class="nav-item"><a href="{% url 'home:contact' %}" class="nav-link">Contact</a></li>
	        </ul>
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->

    <section class="hero-wrap hero-wrap-2" style="background-image: url('/static/images/bg_2.jpg');">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <h1 class="mb-2 bread">  Current News  </h1>
            <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'home:index' %}">Home
            <i class="ion-ios-arrow-forward"></i></a></span> <span> News <i class="ion-ios-arrow-forward"></i></span></p>
          </div>
        </div>
      </div>
    </section>

		<section class="ftco-section">
			<div class="container">
				<div class="row">

{% for item in items %}
					<div class="col-md-12 course d-lg-flex ftco-animate">
						<div class="img" style="background-image: url({{ item.news_image.url }});"></div>
						<div class="text bg-light p-4" style="color: rgba(0,0,0,0.8);">
							<h3><a href="#"> {{ item.title }} </a></h3>
							<p class="subheading"><span> 	{{ item.dated_on }} </span> 9:00am - 10am </p>
							<p> {{ item.description }}        </p>
						</div>
					</div>
{% endfor %}

				</div>
			</div>
		</section>





{% endblock %}